config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  


  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end
  root 'welcome#index'
  resources :docs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
    belongs_to :user

    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
    before_action :find_doc, only: [:show, :edit, :update, :destroy]

    def index
        @docs = Doc.where(user_id: current_user)
    end

    def show
    end

    def new
        @doc = current_user.docs.build
    end

    def create
        @doc = current_user.docs.build(doc_params)

        if @doc.save
            redirect_to @doc
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @doc.update(doc_params)
            redirect_to @doc 
        else
            render 'edit'
        end
    end

    def destroy
        @doc.destroy
        redirect_to docs_path
    end
    
    private
        def find_doc
            @doc = Doc.find(params[:id])
        end

        def doc_params
            params.require(:doc).permit(:title, :content)
        end

    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
    = f.input :title
    = f.input :content
    = f.file_field :avatar 
    = f.button :submit 

app/views/docs/edit.html.haml
%h1 Fix Doc!

= render 'form'

= link_to "Cancel", doc_path

app/views/docs/index.html.haml
- @docs.each do |doc|
    %h2= link_to doc.title, doc 
    %p= time_ago_in_words(doc.created_at)
    %p= truncate(doc.content, length:50)

= link_to "Create Doc", new_doc_path

app/views/docs/new.html.haml
%h1 New Doc!

= render 'form'

app/views/docs/show.html.haml
%h1= @doc.title 
%p= @doc.content 

= link_to "All Docs", docs_path
= link_to "Fix Doc", edit_doc_path(@doc)
= link_to "Trash It", doc_path(@doc), method: :delete, data: {confirm: "Are you sure?"}

app/views/layouts/application.html.haml
%html 
  %head 
    %title FileCabinet | Your life's work! 
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'true'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags 
  %body
    %header
      .header_inner 
        %h1
          = link_to "FileCabinet", root_path, id: "logo" 

        %nav
          - if user_signed_in?
            = link_to "Create Doc", new_doc_path 
            = link_to "Sign Out", destroy_user_session_path, method: :delete 

          - else 
            = link_to "Log In", new_user_session_path 
  %p.notice= notice 
  %p.alert= alert 

  = yield 

app/views/welcome/index.html.haml
#banner 
    .banner_content 
        %h1 File Cabinet 
        %p Your lif's work. Organized, always. 
        %button= link_to "Enter", new_user_registration_path 

#callouts 
    .callout_inner 
        .wrapper 
            .callout 
                %h2 Organize 
                %p Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mauris nunc congue nisi vitae suscipit tellus mauris. Non enim praesent elementum facilisis. Elit pellentesque habitant morbi tristique senectus et netus. Massa enim nec dui nunc mattis enim ut tellus. Diam quis enim lobortis scelerisque fermentum dui faucibus. Bibendum enim facilisis gravida neque convallis. Ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Eget aliquet nibh praesent tristique. Adipiscing elit pellentesque habitant morbi tristique. Vel eros donec ac odio tempor orci. Pellentesque dignissim enim sit amet venenatis. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant.

                Vitae tempus quam pellentesque nec nam aliquam sem. Interdum velit laoreet id donec. Lorem mollis aliquam ut porttitor leo a diam sollicitudin. Integer eget aliquet nibh praesent tristique magna sit amet. Amet facilisis magna etiam tempor orci eu. Non quam lacus suspendisse faucibus interdum. Faucibus in ornare quam viverra orci sagittis. Cras adipiscing enim eu turpis egestas pretium aenean pharetra magna. Habitant morbi tristique senectus et netus et. Proin libero nunc consequat interdum varius sit amet mattis vulputate.

                Sem nulla pharetra diam sit amet. Viverra suspendisse potenti nullam ac tortor. Dignissim enim sit amet venenatis urna cursus. Et leo duis ut diam quam nulla. Ullamcorper a lacus vestibulum sed arcu non odio. At urna condimentum mattis pellentesque id. Vestibulum lectus mauris ultrices eros. Augue neque gravida in fermentum. Aliquet porttitor lacus luctus accumsan. Pellentesque habitant morbi tristique senectus et netus. Sed nisi lacus sed viverra. Massa massa ultricies mi quis hendrerit dolor magna. Facilisis mauris sit amet massa vitae tortor.

                Eget dolor morbi non arcu risus. Pharetra vel turpis nunc eget lorem dolor sed. Aenean vel elit scelerisque mauris pellentesque pulvinar. Phasellus egestas tellus rutrum tellus. At lectus urna duis convallis convallis tellus id interdum. Enim diam vulputate ut pharetra sit amet aliquam. Dolor sit amet consectetur adipiscing elit ut aliquam purus. Felis bibendum ut tristique et egestas quis ipsum suspendisse. Pharetra magna ac placerat vestibulum lectus. Est ullamcorper eget nulla facilisi. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Tempus quam pellentesque nec nam aliquam sem. Pellentesque nec nam aliquam sem et tortor. Dignissim convallis aenean et tortor at.

                Enim nec dui nunc mattis enim ut tellus elementum sagittis. Ullamcorper morbi tincidunt ornare massa. Integer feugiat scelerisque varius morbi enim nunc faucibus. Mi ipsum faucibus vitae aliquet nec ullamcorper sit. Augue eget arcu dictum varius duis. Ullamcorper eget nulla facilisi etiam dignissim diam quis. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est. At varius vel pharetra vel. Eget gravida cum sociis natoque penatibus et. Velit scelerisque in dictum non consectetur a erat nam at. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget nullam. Aenean sed adipiscing diam donec adipiscing tristique risus. Pharetra vel turpis nunc eget lorem dolor. Suspendisse sed nisi lacus sed viverra. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non. Aenean pharetra magna ac placerat. Sed felis eget velit aliquet sagittis id consectetur. Tellus at urna condimentum mattis pellentesque id nibh tortor id.

#bottom_cta 
    .wrapper 
        %h2 Go Ahead! 
        %br
        %button= link_to "Join Now", new_user_registration_path 